#!/bin/bash
# =============================================================
# GitHub Issues Creator — Bookas.pt Master Plan
# Usage: bash create_issues.sh
# Requires: GitHub CLI (gh) installed and authenticated
# Install: https://cli.github.com/
# =============================================================

REPO="FreeAiHub/bookas"

echo "🚀 Creating labels..."

# ── LABELS ────────────────────────────────────────────────────
gh label create "high-priority"  --color "D93F0B" --description "Urgent tasks" --repo $REPO --force
gh label create "setup"          --color "EDEDED" --description "Tool setup & configuration" --repo $REPO --force
gh label create "content"        --color "0E8A16" --description "Blog, social, email content" --repo $REPO --force
gh label create "seo"            --color "E4E669" --description "SEO tasks" --repo $REPO --force
gh label create "email"          --color "1D76DB" --description "Email campaigns" --repo $REPO --force
gh label create "automation"     --color "5319E7" --description "Scripts and automation" --repo $REPO --force
gh label create "analytics"      --color "F9D0C4" --description "Reports and analytics" --repo $REPO --force
gh label create "recurring"      --color "BFD4F2" --description "Weekly/monthly recurring tasks" --repo $REPO --force
gh label create "campaign"       --color "C2E0C6" --description "Marketing campaigns" --repo $REPO --force

echo "✅ Labels created!"
echo ""
echo "📅 Creating Milestones..."

# ── MILESTONES ────────────────────────────────────────────────
gh api repos/$REPO/milestones -f title="Week 1 — Foundation" -f description="SEO setup, Google tools, first blog article" -f due_on="2026-03-22T00:00:00Z"
gh api repos/$REPO/milestones -f title="March 2026" -f description="March campaigns and content" -f due_on="2026-03-31T00:00:00Z"
gh api repos/$REPO/milestones -f title="April 2026 — World Book Day" -f description="April campaigns — Dia Mundial do Livro is MAIN event" -f due_on="2026-04-30T00:00:00Z"
gh api repos/$REPO/milestones -f title="May 2026 — Dia da Mãe" -f description="Mother's Day campaign and ongoing content" -f due_on="2026-05-31T00:00:00Z"

echo "✅ Milestones created!"
echo ""
echo "📋 Creating Issues..."

# ══════════════════════════════════════════════════════════════
# WEEK 1 — FOUNDATION (HIGH PRIORITY)
# ══════════════════════════════════════════════════════════════

gh issue create \
  --repo $REPO \
  --title "[SEO] Install & configure Rank Math Pro on bookas.pt" \
  --label "setup,seo,high-priority" \
  --body "## 🎯 Goal
Install and fully configure Rank Math Pro WordPress plugin for bookas.pt.

## ✅ Tasks
- [ ] Purchase Rank Math Pro license (€7/month)
- [ ] Install plugin on WordPress
- [ ] Configure homepage meta title: *'Bookas — Livraria Online Portugal | Livros com 10% Desconto | Portes Grátis a partir de €15'*
- [ ] Fix all meta titles for main category pages
- [ ] Fix all meta descriptions
- [ ] Enable Product schema for all book pages (auto)
- [ ] Connect Rank Math to Google Search Console

## 📎 References
- Rank Math Pro: https://rankmath.com
- Target meta title from Master Plan

## 🏷️ Definition of Done
All pages have proper meta titles, descriptions, and schema. Rank Math score >70 on homepage."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[SEO] Setup Google Search Console + submit sitemap" \
  --label "setup,seo,high-priority" \
  --body "## 🎯 Goal
Connect bookas.pt to Google Search Console and submit sitemap for indexing.

## ✅ Tasks
- [ ] Verify bookas.pt domain ownership in GSC
- [ ] Submit sitemap.xml (generated by Rank Math)
- [ ] Check for crawl errors
- [ ] Set target country: Portugal 🇵🇹
- [ ] Note current index status (baseline)

## 🏷️ Definition of Done
Sitemap accepted, 0 critical errors, domain verified."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[CONTENT] First blog article — Novos Lançamentos Março 2026" \
  --label "content,seo,high-priority" \
  --body "## 🎯 Goal
Publish first blog article targeting Portuguese search traffic.

## ✅ Tasks
- [ ] Research keywords: 'lançamentos março 2026', 'novos livros março 2026'
- [ ] Draft article (800–1200 words) using Claude Pro
- [ ] Focus on promobooks.net titles FIRST, then exclusive publishers
- [ ] Add Rank Math SEO optimization (score >80)
- [ ] Add internal links to product pages
- [ ] Publish and submit URL to GSC for indexing

## 📝 Article Structure
1. Intro — what's new this month
2. Top 5 highlights (promobooks.net first)
3. Exclusive publishers new releases
4. Call to action — 'Portes grátis a partir de €15'

## 🏷️ Definition of Done
Article published, indexed, Rank Math score >80."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[EMAIL] Setup welcome sequence in Brevo/E-goi" \
  --label "email,setup,high-priority" \
  --body "## 🎯 Goal
Configure automated email sequences for new subscribers and buyers.

## ✅ Tasks

### Buyer sequence:
- [ ] Email 1: Order confirmation (immediate)
- [ ] Email 2: Reminder 1 week before release date
- [ ] Email 3: Shipping notification
- [ ] Email 4: Review request (7 days after delivery)

### Non-buyer sequence (email captured):
- [ ] Email 1: Thank you (immediate)
- [ ] Email 2: Related recommendations (Day 5)
- [ ] Email 3: Release day alert

### Welcome offer:
- [ ] Configure free surprise book offer from promobooks.net on first purchase
- [ ] Note: NO extra % discount (not allowed by Portuguese law)

## 🏷️ Definition of Done
Both sequences live and tested with test email addresses."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[SETUP] Google Merchant Center — product feed configuration" \
  --label "setup,seo" \
  --body "## 🎯 Goal
Setup Google Merchant Center to display Bookas.pt books in Google Shopping.

## ✅ Tasks
- [ ] Create Google Merchant Center account
- [ ] Verify bookas.pt domain
- [ ] Configure WooCommerce product feed plugin
- [ ] Map fields: title, ISBN, price, availability, image
- [ ] Submit feed and resolve errors
- [ ] Link to Google Ads (future)

## 🏷️ Definition of Done
Feed accepted, products appearing in Merchant Center dashboard."

# ══════════════════════════════════════════════════════════════
# MARCH 2026 CAMPAIGNS
# ══════════════════════════════════════════════════════════════

gh issue create \
  --repo $REPO \
  --title "[CAMPAIGN] Dia Internacional da Mulher — March 8" \
  --label "campaign,content,email" \
  --body "## 🎯 Goal
Execute Dia da Mulher (March 8) campaign across all channels.

## ✅ Tasks
- [ ] Create banner: 'Livros escritos por Mulheres'
- [ ] Select 8–10 books by female authors (promobooks.net first)
- [ ] Write email campaign (send March 7 morning)
- [ ] Create 2 social posts (Instagram + Facebook)
- [ ] Publish blog post if time allows

## 🏷️ Definition of Done
Banner live, email sent, social posts published on March 8."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[CAMPAIGN] Dia Mundial da Poesia — March 21" \
  --label "campaign,content" \
  --body "## 🎯 Goal
Create content for World Poetry Day targeting Portuguese poetry books.

## ✅ Tasks
- [ ] Blog post: '10 Livros de Poesia Portuguesa'
- [ ] 2 social posts with poetry quotes
- [ ] Focus on promobooks.net poetry titles

## 🏷️ Definition of Done
Blog published + 2 social posts live on March 21."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[CONTENT] Banners for April — Deadline March 28" \
  --label "content,high-priority,campaign" \
  --body "## 🎯 Goal
Produce all April banners before March 28 deadline.

## ✅ Tasks
- [ ] Confirm with João: Author of Month (April)
- [ ] Confirm with João: Theme of Month (April)
- [ ] Design Author of Month banner
- [ ] Design Theme of Month banner
- [ ] Design World Book Day (April 23) banner
- [ ] Design Dia da Liberdade (April 25) banner
- [ ] Upload all banners to Google Drive

## ⚠️ DEADLINE: March 28, 2026

## 🏷️ Definition of Done
All 4 banners delivered and approved by João before March 28."

# ══════════════════════════════════════════════════════════════
# APRIL 2026 — MAIN EVENT
# ══════════════════════════════════════════════════════════════

gh issue create \
  --repo $REPO \
  --title "[CAMPAIGN] ⭐ Dia Mundial do Livro — April 23 (MAIN EVENT)" \
  --label "campaign,content,email,high-priority" \
  --body "## 🎯 Goal
Execute the biggest April campaign — World Book Day (April 23).

## ✅ Tasks

### Content:
- [ ] Blog: '23 Livros Essenciais para Ler em 2026'
- [ ] Social countdown posts (Apr 20, 21, 22, 23)
- [ ] Special landing page or category highlight

### Email:
- [ ] Email announcement (send April 22)
- [ ] Email day-of (April 23)

### Promo:
- [ ] 1-day special promotion — confirm details with João
- [ ] Update homepage banner

## 📅 Timeline
- Apr 16: Content drafted
- Apr 20: Social countdown starts
- Apr 22: Email scheduled
- Apr 23: ALL LIVE 🚀

## 🏷️ Definition of Done
All assets live on April 23. Email sent. Blog published."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[CAMPAIGN] Dia da Liberdade — April 25" \
  --label "campaign,content" \
  --body "## 🎯 Goal
Create curated list content for April 25 — Portuguese Freedom Day.

## ✅ Tasks
- [ ] Curated list: 'Livros sobre o 25 de Abril'
- [ ] Blog post with list + context
- [ ] 1–2 social posts
- [ ] Email mention (can combine with Apr 23 email)

## 🏷️ Definition of Done
Blog published + social posts live on April 25."

# ══════════════════════════════════════════════════════════════
# RECURRING WEEKLY TASKS
# ══════════════════════════════════════════════════════════════

gh issue create \
  --repo $REPO \
  --title "[RECURRING] Weekly email campaign — every Tuesday" \
  --label "recurring,email" \
  --body "## 🎯 Goal
Send weekly email campaign every Tuesday via Brevo/E-goi.

## ✅ Weekly Checklist
- [ ] Receive new releases Excel from João (Friday)
- [ ] Select top 3–5 books for campaign
- [ ] Write email copy (subject line + body) using Claude Pro
- [ ] Schedule send for Tuesday morning (9:00 AM PT time)
- [ ] Monitor open rate + click rate
- [ ] Note results in weekly report

## 📊 Target Metrics
- Open rate: >25%
- Click rate: >3%

## 🏷️ This is a permanent recurring process — do not close."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[RECURRING] Weekly social media posts — 3-5 per week" \
  --label "recurring,content" \
  --body "## 🎯 Goal
Maintain consistent social presence on Instagram and Facebook.

## ✅ Weekly Checklist
- [ ] Monday: Plan week's posts based on new releases + calendar
- [ ] Create 3–5 posts (mix of new releases, thematic, engagement)
- [ ] Thursday: Publish pre-order feature posts
- [ ] Use Claude Pro for caption copy in Portuguese
- [ ] Track engagement (likes, shares, saves, reach)

## 📱 Platforms
- Instagram
- Facebook

## Content Mix
- 40% New releases / pre-orders
- 30% Thematic (Author/Theme of Month)
- 20% Seasonal / campaign
- 10% Engagement (questions, polls)

## 🏷️ This is a permanent recurring process — do not close."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[RECURRING] Friday performance report to João" \
  --label "recurring,analytics" \
  --body "## 🎯 Goal
Send weekly performance report to João every Friday.

## ✅ Report Template
- [ ] Traffic: sessions, users, bounce rate (vs last week)
- [ ] Sales: orders, revenue, top products
- [ ] Pre-orders: which titles, quantities
- [ ] Email: open rate, click rate, unsubscribes
- [ ] Social: reach, engagement, top post
- [ ] SEO: ranking changes for target keywords
- [ ] Next week plan: content scheduled

## 📊 Tools
- Google Analytics / Search Console
- Brevo/E-goi dashboard
- WooCommerce reports

## 🏷️ This is a permanent recurring process — do not close."

# ══════════════════════════════════════════════════════════════
# AUTOMATION & TECHNICAL
# ══════════════════════════════════════════════════════════════

gh issue create \
  --repo $REPO \
  --title "[AUTOMATION] Social post generator from new releases Excel" \
  --label "automation" \
  --body "## 🎯 Goal
Build script that reads João's weekly Excel file and auto-generates social media post drafts using Claude API.

## ✅ Tasks
- [ ] Define Excel input format (columns: ISBN, title, author, price, release date, synopsis)
- [ ] Build parser for Excel file (pandas)
- [ ] Integrate Claude API to generate PT captions
- [ ] Output: ready-to-post text for Instagram + Facebook
- [ ] Add image path lookup by ISBN
- [ ] Test with real data samples

## 🛠️ Tech Stack
- Python + pandas (Excel parsing)
- Anthropic Claude API (caption generation)
- Output: JSON or markdown file with posts

## 📁 Files
- \`automation/social_post_gen.py\`
- \`data_samples/releases_example.xlsx\`

## 🏷️ Definition of Done
Script runs on Excel input and outputs 5 ready social posts."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[AUTOMATION] Blog article generator — Claude API pipeline" \
  --label "automation,content" \
  --body "## 🎯 Goal
Automate blog article generation using Claude API for Portuguese SEO content.

## ✅ Tasks
- [ ] Design prompt template for Portuguese book blog articles
- [ ] Include: keyword targeting, internal links, promobooks.net priority
- [ ] Build script: input keyword → output draft article
- [ ] Add Rank Math SEO checklist validation
- [ ] Test with 3 different keywords
- [ ] Document usage for non-technical use

## 🛠️ Tech Stack
- Python
- Anthropic Claude API (claude-sonnet-4-20250514)
- Output: Markdown ready for WordPress

## 📁 Files
- \`content/blog_generator.py\`
- \`content/prompt_templates/\`

## 🏷️ Definition of Done
Script generates 800-word PT article from keyword input in <30 seconds."

# ─────────────────────────────────────────────────────────────

gh issue create \
  --repo $REPO \
  --title "[SEO] Link building tests — Month 2 (€80 budget)" \
  --label "seo" \
  --body "## 🎯 Goal
Test link building services to improve bookas.pt domain authority.

## ✅ Tasks
- [ ] Research 3–5 link building services (Portuguese market preferred)
- [ ] Start with small test orders (€20–30 each)
- [ ] Track domain authority before (baseline)
- [ ] Place test orders
- [ ] Monitor results after 30 days
- [ ] Report ROI to João

## 💰 Budget: €80/month

## 📊 Metrics to track
- Domain Rating (Ahrefs/Moz)
- Number of referring domains
- Organic traffic change

## 🏷️ Definition of Done
3 services tested, results documented, recommendation made."

echo ""
echo "🎉 ALL ISSUES CREATED SUCCESSFULLY!"
echo ""
echo "📋 Next steps:"
echo "1. Go to: https://github.com/FreeAiHub/bookas/issues"
echo "2. Create a Project board (Kanban)"
echo "3. Add all issues to the board"
echo "4. Start working — close issues as you complete tasks!"
